name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue is stale and will be closed soon.  If you feel this issue is relevant, please comment to keep it active.'
          stale-pr-message: 'This PR is stale and will be closed soon. If you feel this PR is relevant, please comment and/or seek out reviewers.'
